package kz.greepto.gpen.drawport;

public enum Kursor {
  ARROW, WAIT, CROSS, APPSTARTING, HELP, SIZEALL, SIZENESW, SIZENS, SIZENWSE, SIZEWE, SIZEN, SIZES,
  SIZEE, SIZEW, SIZENE, SIZESE, SIZESW, SIZENW, UPARROW, IBEAM, NO, HAND;
}
