package kz.pompei.dao.i;

public interface VT {
  String person = " select  x.person,  x.createdAt ,x1.type ,x2.address from (select u.* from m_person u, tts where u.createdAt <= tts.ts) x left join( select person, type from ( select m.*, row_number() over (partition by m.person order by m.ts desc ) as rn__ from m_person_type m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.person = x.person left join( select person, address from ( select m.*, row_number() over (partition by m.person order by m.ts desc ) as rn__ from m_person_address m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.person = x.person";
  String person_type = " select person, type from ( select m.*, row_number() over (partition by m.person order by m.ts desc ) as rn__ from m_person_type m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String person_address = " select person, address from ( select m.*, row_number() over (partition by m.person order by m.ts desc ) as rn__ from m_person_address m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String phone = " select  x.person,  x.annType,  x.createdAt ,x1.type ,x2.value ,x3.smsTemplate from (select u.* from m_phone u, tts where u.createdAt <= tts.ts) x left join( select person, annType, type from ( select m.*, row_number() over (partition by m.person, m.annType order by m.ts desc ) as rn__ from m_phone_type m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.person = x.person and x1.annType = x.annType left join( select person, annType, value from ( select m.*, row_number() over (partition by m.person, m.annType order by m.ts desc ) as rn__ from m_phone_value m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.person = x.person and x2.annType = x.annType left join( select person, annType, smsTemplate from ( select m.*, row_number() over (partition by m.person, m.annType order by m.ts desc ) as rn__ from m_phone_smsTemplate m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x3 on x3.person = x.person and x3.annType = x.annType";
  String phone_type = " select person, annType, type from ( select m.*, row_number() over (partition by m.person, m.annType order by m.ts desc ) as rn__ from m_phone_type m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String phone_value = " select person, annType, value from ( select m.*, row_number() over (partition by m.person, m.annType order by m.ts desc ) as rn__ from m_phone_value m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String phone_smsTemplate = " select person, annType, smsTemplate from ( select m.*, row_number() over (partition by m.person, m.annType order by m.ts desc ) as rn__ from m_phone_smsTemplate m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String contract = " select  x.contract,  x.createdAt ,x1.nomer ,x2.summa ,x3.productType ,x4.client ,x5.lastPkbRequest ,x6.asd from (select u.* from m_contract u, tts where u.createdAt <= tts.ts) x left join( select contract, nomer from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_nomer m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.contract = x.contract left join( select contract, summa from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_summa m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.contract = x.contract left join( select contract, productType from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_productType m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x3 on x3.contract = x.contract left join( select contract, client from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_client m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x4 on x4.contract = x.contract left join( select contract, lastPkbRequest from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_lastPkbRequest m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x5 on x5.contract = x.contract left join( select contract, asd from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_asd m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x6 on x6.contract = x.contract";
  String contract_nomer = " select contract, nomer from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_nomer m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String contract_summa = " select contract, summa from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_summa m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String contract_productType = " select contract, productType from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_productType m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String contract_client = " select contract, client from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_client m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String contract_lastPkbRequest = " select contract, lastPkbRequest from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_lastPkbRequest m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String contract_asd = " select contract, asd from ( select m.*, row_number() over (partition by m.contract order by m.ts desc ) as rn__ from m_contract_asd m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String phoneType = " select  x.phoneType,  x.createdAt ,x1.name from (select u.* from m_phoneType u, tts where u.createdAt <= tts.ts) x left join( select phoneType, name from ( select m.*, row_number() over (partition by m.phoneType order by m.ts desc ) as rn__ from m_phoneType_name m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.phoneType = x.phoneType";
  String phoneType_name = " select phoneType, name from ( select m.*, row_number() over (partition by m.phoneType order by m.ts desc ) as rn__ from m_phoneType_name m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String naturalPerson = " select  x.naturalPerson,  x.createdAt ,x1.surname ,x2.name ,x3.birthdate ,x4.iin from (select u.* from m_naturalPerson u, tts where u.createdAt <= tts.ts) x left join( select naturalPerson, surname from ( select m.*, row_number() over (partition by m.naturalPerson order by m.ts desc ) as rn__ from m_naturalPerson_surname m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.naturalPerson = x.naturalPerson left join( select naturalPerson, name from ( select m.*, row_number() over (partition by m.naturalPerson order by m.ts desc ) as rn__ from m_naturalPerson_name m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.naturalPerson = x.naturalPerson left join( select naturalPerson, birthdate from ( select m.*, row_number() over (partition by m.naturalPerson order by m.ts desc ) as rn__ from m_naturalPerson_birthdate m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x3 on x3.naturalPerson = x.naturalPerson left join( select naturalPerson, iin from ( select m.*, row_number() over (partition by m.naturalPerson order by m.ts desc ) as rn__ from m_naturalPerson_iin m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x4 on x4.naturalPerson = x.naturalPerson";
  String naturalPerson_surname = " select naturalPerson, surname from ( select m.*, row_number() over (partition by m.naturalPerson order by m.ts desc ) as rn__ from m_naturalPerson_surname m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String naturalPerson_name = " select naturalPerson, name from ( select m.*, row_number() over (partition by m.naturalPerson order by m.ts desc ) as rn__ from m_naturalPerson_name m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String naturalPerson_birthdate = " select naturalPerson, birthdate from ( select m.*, row_number() over (partition by m.naturalPerson order by m.ts desc ) as rn__ from m_naturalPerson_birthdate m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String naturalPerson_iin = " select naturalPerson, iin from ( select m.*, row_number() over (partition by m.naturalPerson order by m.ts desc ) as rn__ from m_naturalPerson_iin m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String legalPerson = " select  x.legalPerson,  x.createdAt ,x1.name ,x2.fullname ,x3.bin from (select u.* from m_legalPerson u, tts where u.createdAt <= tts.ts) x left join( select legalPerson, name from ( select m.*, row_number() over (partition by m.legalPerson order by m.ts desc ) as rn__ from m_legalPerson_name m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.legalPerson = x.legalPerson left join( select legalPerson, fullname from ( select m.*, row_number() over (partition by m.legalPerson order by m.ts desc ) as rn__ from m_legalPerson_fullname m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.legalPerson = x.legalPerson left join( select legalPerson, bin from ( select m.*, row_number() over (partition by m.legalPerson order by m.ts desc ) as rn__ from m_legalPerson_bin m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x3 on x3.legalPerson = x.legalPerson";
  String legalPerson_name = " select legalPerson, name from ( select m.*, row_number() over (partition by m.legalPerson order by m.ts desc ) as rn__ from m_legalPerson_name m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String legalPerson_fullname = " select legalPerson, fullname from ( select m.*, row_number() over (partition by m.legalPerson order by m.ts desc ) as rn__ from m_legalPerson_fullname m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String legalPerson_bin = " select legalPerson, bin from ( select m.*, row_number() over (partition by m.legalPerson order by m.ts desc ) as rn__ from m_legalPerson_bin m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String productType = " select  x.productType,  x.createdAt ,x1.pkbId ,x2.name from (select u.* from m_productType u, tts where u.createdAt <= tts.ts) x left join( select productType, pkbId from ( select m.*, row_number() over (partition by m.productType order by m.ts desc ) as rn__ from m_productType_pkbId m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.productType = x.productType left join( select productType, name from ( select m.*, row_number() over (partition by m.productType order by m.ts desc ) as rn__ from m_productType_name m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.productType = x.productType";
  String productType_pkbId = " select productType, pkbId from ( select m.*, row_number() over (partition by m.productType order by m.ts desc ) as rn__ from m_productType_pkbId m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String productType_name = " select productType, name from ( select m.*, row_number() over (partition by m.productType order by m.ts desc ) as rn__ from m_productType_name m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String pkbResultParamAnn = " select  x.pkbResultParam1,  x.pkbResultParam2,  x.name,  x.createdAt ,x1.valueStr ,x2.valueInt ,x3.type ,x4.hello ,x5.goodby from (select u.* from m_pkbResultParamAnn u, tts where u.createdAt <= tts.ts) x left join( select pkbResultParam1, pkbResultParam2, name, valueStr from ( select m.*, row_number() over (partition by m.pkbResultParam1, m.pkbResultParam2, m.name order by m.ts desc ) as rn__ from m_pkbResultParamAnn_valueStr m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.pkbResultParam1 = x.pkbResultParam1 and x1.pkbResultParam2 = x.pkbResultParam2 and x1.name = x.name left join( select pkbResultParam1, pkbResultParam2, name, valueInt from ( select m.*, row_number() over (partition by m.pkbResultParam1, m.pkbResultParam2, m.name order by m.ts desc ) as rn__ from m_pkbResultParamAnn_valueInt m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.pkbResultParam1 = x.pkbResultParam1 and x2.pkbResultParam2 = x.pkbResultParam2 and x2.name = x.name left join( select pkbResultParam1, pkbResultParam2, name, type from ( select m.*, row_number() over (partition by m.pkbResultParam1, m.pkbResultParam2, m.name order by m.ts desc ) as rn__ from m_pkbResultParamAnn_type m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x3 on x3.pkbResultParam1 = x.pkbResultParam1 and x3.pkbResultParam2 = x.pkbResultParam2 and x3.name = x.name left join( select pkbResultParam1, pkbResultParam2, name, hello from ( select m.*, row_number() over (partition by m.pkbResultParam1, m.pkbResultParam2, m.name order by m.ts desc ) as rn__ from m_pkbResultParamAnn_hello m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x4 on x4.pkbResultParam1 = x.pkbResultParam1 and x4.pkbResultParam2 = x.pkbResultParam2 and x4.name = x.name left join( select pkbResultParam1, pkbResultParam2, name, goodby from ( select m.*, row_number() over (partition by m.pkbResultParam1, m.pkbResultParam2, m.name order by m.ts desc ) as rn__ from m_pkbResultParamAnn_goodby m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x5 on x5.pkbResultParam1 = x.pkbResultParam1 and x5.pkbResultParam2 = x.pkbResultParam2 and x5.name = x.name";
  String pkbResultParamAnn_valueStr = " select pkbResultParam1, pkbResultParam2, name, valueStr from ( select m.*, row_number() over (partition by m.pkbResultParam1, m.pkbResultParam2, m.name order by m.ts desc ) as rn__ from m_pkbResultParamAnn_valueStr m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String pkbResultParamAnn_valueInt = " select pkbResultParam1, pkbResultParam2, name, valueInt from ( select m.*, row_number() over (partition by m.pkbResultParam1, m.pkbResultParam2, m.name order by m.ts desc ) as rn__ from m_pkbResultParamAnn_valueInt m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String pkbResultParamAnn_type = " select pkbResultParam1, pkbResultParam2, name, type from ( select m.*, row_number() over (partition by m.pkbResultParam1, m.pkbResultParam2, m.name order by m.ts desc ) as rn__ from m_pkbResultParamAnn_type m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String pkbResultParamAnn_hello = " select pkbResultParam1, pkbResultParam2, name, hello from ( select m.*, row_number() over (partition by m.pkbResultParam1, m.pkbResultParam2, m.name order by m.ts desc ) as rn__ from m_pkbResultParamAnn_hello m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String pkbResultParamAnn_goodby = " select pkbResultParam1, pkbResultParam2, name, goodby from ( select m.*, row_number() over (partition by m.pkbResultParam1, m.pkbResultParam2, m.name order by m.ts desc ) as rn__ from m_pkbResultParamAnn_goodby m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String pkbResult = " select  x.pkbResult,  x.createdAt ,x1.isOK ,x2.xmlContent from (select u.* from m_pkbResult u, tts where u.createdAt <= tts.ts) x left join( select pkbResult, isOK from ( select m.*, row_number() over (partition by m.pkbResult order by m.ts desc ) as rn__ from m_pkbResult_isOK m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.pkbResult = x.pkbResult left join( select pkbResult, xmlContent from ( select m.*, row_number() over (partition by m.pkbResult order by m.ts desc ) as rn__ from m_pkbResult_xmlContent m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.pkbResult = x.pkbResult";
  String pkbResult_isOK = " select pkbResult, isOK from ( select m.*, row_number() over (partition by m.pkbResult order by m.ts desc ) as rn__ from m_pkbResult_isOK m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String pkbResult_xmlContent = " select pkbResult, xmlContent from ( select m.*, row_number() over (partition by m.pkbResult order by m.ts desc ) as rn__ from m_pkbResult_xmlContent m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String pkbResultParam = " select  x.pkbResult,  x.name,  x.createdAt ,x1.value from (select u.* from m_pkbResultParam u, tts where u.createdAt <= tts.ts) x left join( select pkbResult, name, value from ( select m.*, row_number() over (partition by m.pkbResult, m.name order by m.ts desc ) as rn__ from m_pkbResultParam_value m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.pkbResult = x.pkbResult and x1.name = x.name";
  String pkbResultParam_value = " select pkbResult, name, value from ( select m.*, row_number() over (partition by m.pkbResult, m.name order by m.ts desc ) as rn__ from m_pkbResultParam_value m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String address = " select  x.address,  x.createdAt ,x1.street ,x2.flat from (select u.* from m_address u, tts where u.createdAt <= tts.ts) x left join( select address, street from ( select m.*, row_number() over (partition by m.address order by m.ts desc ) as rn__ from m_address_street m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.address = x.address left join( select address, flat from ( select m.*, row_number() over (partition by m.address order by m.ts desc ) as rn__ from m_address_flat m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.address = x.address";
  String address_street = " select address, street from ( select m.*, row_number() over (partition by m.address order by m.ts desc ) as rn__ from m_address_street m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String address_flat = " select address, flat from ( select m.*, row_number() over (partition by m.address order by m.ts desc ) as rn__ from m_address_flat m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String asd = " select  x.asd,  x.createdAt ,x1.name ,x2.wow1 ,x2.wow2 ,x2.wow3 from (select u.* from m_asd u, tts where u.createdAt <= tts.ts) x left join( select asd, name from ( select m.*, row_number() over (partition by m.asd order by m.ts desc ) as rn__ from m_asd_name m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.asd = x.asd left join( select asd, wow1, wow2, wow3 from ( select m.*, row_number() over (partition by m.asd order by m.ts desc ) as rn__ from m_asd_wow m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.asd = x.asd";
  String asd_name = " select asd, name from ( select m.*, row_number() over (partition by m.asd order by m.ts desc ) as rn__ from m_asd_name m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String asd_wow = " select asd, wow1, wow2, wow3 from ( select m.*, row_number() over (partition by m.asd order by m.ts desc ) as rn__ from m_asd_wow m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String smsTemplate = " select  x.smsTemplate,  x.createdAt ,x1.templateContent ,x2.phone1 ,x2.phone2 from (select u.* from m_smsTemplate u, tts where u.createdAt <= tts.ts) x left join( select smsTemplate, templateContent from ( select m.*, row_number() over (partition by m.smsTemplate order by m.ts desc ) as rn__ from m_smsTemplate_templateContent m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.smsTemplate = x.smsTemplate left join( select smsTemplate, phone1, phone2 from ( select m.*, row_number() over (partition by m.smsTemplate order by m.ts desc ) as rn__ from m_smsTemplate_phone m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.smsTemplate = x.smsTemplate";
  String smsTemplate_templateContent = " select smsTemplate, templateContent from ( select m.*, row_number() over (partition by m.smsTemplate order by m.ts desc ) as rn__ from m_smsTemplate_templateContent m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String smsTemplate_phone = " select smsTemplate, phone1, phone2 from ( select m.*, row_number() over (partition by m.smsTemplate order by m.ts desc ) as rn__ from m_smsTemplate_phone m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
  String pkbRequest = " select  x.pkbRequest,  x.createdAt ,x1.contract ,x2.idNumber ,x3.reportCode from (select u.* from m_pkbRequest u, tts where u.createdAt <= tts.ts) x left join( select pkbRequest, contract from ( select m.*, row_number() over (partition by m.pkbRequest order by m.ts desc ) as rn__ from m_pkbRequest_contract m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x1 on x1.pkbRequest = x.pkbRequest left join( select pkbRequest, idNumber from ( select m.*, row_number() over (partition by m.pkbRequest order by m.ts desc ) as rn__ from m_pkbRequest_idNumber m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x2 on x2.pkbRequest = x.pkbRequest left join( select pkbRequest, reportCode from ( select m.*, row_number() over (partition by m.pkbRequest order by m.ts desc ) as rn__ from m_pkbRequest_reportCode m , tts where m.ts <= tts.ts ) x where x.rn__ = 1) x3 on x3.pkbRequest = x.pkbRequest";
  String pkbRequest_contract = " select pkbRequest, contract from ( select m.*, row_number() over (partition by m.pkbRequest order by m.ts desc ) as rn__ from m_pkbRequest_contract m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String pkbRequest_idNumber = " select pkbRequest, idNumber from ( select m.*, row_number() over (partition by m.pkbRequest order by m.ts desc ) as rn__ from m_pkbRequest_idNumber m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  String pkbRequest_reportCode = " select pkbRequest, reportCode from ( select m.*, row_number() over (partition by m.pkbRequest order by m.ts desc ) as rn__ from m_pkbRequest_reportCode m , tts where m.ts <= tts.ts ) x where x.rn__ = 1";
  
}
